name: CI

on: push

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Nuxt prepare
        run: pnpx nuxt prepare

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Set playwright path and Get playwright version
        run: |
          echo "PLAYWRIGHT_BROWSERS_PATH=${HOME}/.cache/playwright-bin" >> $GITHUB_ENV
          PLAYWRIGHT_VERSION="$(pnpm ls --json playwright-core | jq --raw-output '.[0].devDependencies["playwright-core"].version')"
          echo "PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}" >> $GITHUB_ENV

      - name: Cache playwright bin
        uses: actions/cache@v3
        id: playwright-cache
        with:
          key: ${{ runner.os }}-playwright-bin-v1-${{ env.PLAYWRIGHT_VERSION }}
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          restore-keys: |
            ${{ runner.os }}-playwright-bin-v1-

      - name: Install playwright
        run: |
          if ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}; then
            pnpm playwright-core install --with-deps chromium
          else
            pnpm playwright-core install-deps chromium
          fi

      - name: Run generate
        run: pnpm run generate

      - name: Run e2e test
        run: pnpm run test:ci

  deploy:
    needs:
      - lint
      - test
    uses: ./.github/workflows/vercel.yaml
    secrets: inherit
