name: CI

on: push

permissions: {}

env:
  PLAYWRIGHT_VERSION: ''
  PLAYWRIGHT_BROWSERS_PATH: ''
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Run unit test
        run: pnpm run test:unit

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set playwright path and Get playwright version
        run: |
          echo "PLAYWRIGHT_BROWSERS_PATH=${HOME}/.cache/playwright-bin" >> $GITHUB_ENV
          PLAYWRIGHT_VERSION="$(pnpm ls --json playwright-core | jq --raw-output '.[0].devDependencies["playwright-core"].version')"
          echo "PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}" >> $GITHUB_ENV

      - name: Cache playwright bin
        uses: actions/cache@v4
        id: playwright-cache
        with:
          key: ${{ runner.os }}-playwright-bin-v1-${{ env.PLAYWRIGHT_VERSION }}
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          restore-keys: |
            ${{ runner.os }}-playwright-bin-v1-

      - name: Install playwright
        run: |
          if ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}; then
            pnpm playwright-core install --with-deps chromium
          else
            pnpm playwright-core install-deps chromium
          fi

      - name: Run generate
        run: pnpm run generate

      - name: Run e2e test
        run: pnpm run test:e2e
