name: CI

on: push

permissions: {}

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: ./.github/actions/install-playwright

      - name: Lint
        run: pnpm run lint

      - name: Run unit test
        run: pnpm run test:unit --coverage

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: ./.github/actions/install-playwright

      - name: Run build
        run: pnpm run build --logLevel=silent

      - name: Run e2e test
        run: pnpm run test:e2e
