name: Vercel Deployment

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]

permissions: {}

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  prod:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    environment: Production

    env:
      NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
      NUXT_PUBLIC_CONTACT_URL: ${{ vars.VERCEL_PROJECT_ID }}
      NUXT_PUBLIC_GTAG_ID: ${{ vars.NUXT_PUBLIC_GTAG_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run generate
        run: pnpm run generate

      - name: Deploy to vercel
        run: |
          VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
          VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
          pnpx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
